export const REPOSITORIES_MOCK = [
  {
    id: 452338847,
    node_id: "R_kgDOGvYknw",
    name: "5by5-director",
    full_name: "dan/5by5-director",
    private: false,
    owner: {
      login: "dan",
      id: 219,
      node_id: "MDQ6VXNlcjIxOQ==",
      avatar_url: "https://avatars.githubusercontent.com/u/219?v=4",
      gravatar_id: "",
      url: "https://api.github.com/users/dan",
      html_url: "https://github.com/dan",
      followers_url: "https://api.github.com/users/dan/followers",
      following_url: "https://api.github.com/users/dan/following{/other_user}",
      gists_url: "https://api.github.com/users/dan/gists{/gist_id}",
      starred_url: "https://api.github.com/users/dan/starred{/owner}{/repo}",
      subscriptions_url: "https://api.github.com/users/dan/subscriptions",
      organizations_url: "https://api.github.com/users/dan/orgs",
      repos_url: "https://api.github.com/users/dan/repos",
      events_url: "https://api.github.com/users/dan/events{/privacy}",
      received_events_url: "https://api.github.com/users/dan/received_events",
      type: "User",
      user_view_type: "public",
      site_admin: false,
    },
    html_url: "https://github.com/dan/5by5-director",
    description:
      "Sinatra app to handle straggler downloads from the old 5by5.tv",
    fork: false,
    url: "https://api.github.com/repos/dan/5by5-director",
    forks_url: "https://api.github.com/repos/dan/5by5-director/forks",
    keys_url: "https://api.github.com/repos/dan/5by5-director/keys{/key_id}",
    collaborators_url:
      "https://api.github.com/repos/dan/5by5-director/collaborators{/collaborator}",
    teams_url: "https://api.github.com/repos/dan/5by5-director/teams",
    hooks_url: "https://api.github.com/repos/dan/5by5-director/hooks",
    issue_events_url:
      "https://api.github.com/repos/dan/5by5-director/issues/events{/number}",
    events_url: "https://api.github.com/repos/dan/5by5-director/events",
    assignees_url:
      "https://api.github.com/repos/dan/5by5-director/assignees{/user}",
    branches_url:
      "https://api.github.com/repos/dan/5by5-director/branches{/branch}",
    tags_url: "https://api.github.com/repos/dan/5by5-director/tags",
    blobs_url: "https://api.github.com/repos/dan/5by5-director/git/blobs{/sha}",
    git_tags_url:
      "https://api.github.com/repos/dan/5by5-director/git/tags{/sha}",
    git_refs_url:
      "https://api.github.com/repos/dan/5by5-director/git/refs{/sha}",
    trees_url: "https://api.github.com/repos/dan/5by5-director/git/trees{/sha}",
    statuses_url:
      "https://api.github.com/repos/dan/5by5-director/statuses/{sha}",
    languages_url: "https://api.github.com/repos/dan/5by5-director/languages",
    stargazers_url: "https://api.github.com/repos/dan/5by5-director/stargazers",
    contributors_url:
      "https://api.github.com/repos/dan/5by5-director/contributors",
    subscribers_url:
      "https://api.github.com/repos/dan/5by5-director/subscribers",
    subscription_url:
      "https://api.github.com/repos/dan/5by5-director/subscription",
    commits_url: "https://api.github.com/repos/dan/5by5-director/commits{/sha}",
    git_commits_url:
      "https://api.github.com/repos/dan/5by5-director/git/commits{/sha}",
    comments_url:
      "https://api.github.com/repos/dan/5by5-director/comments{/number}",
    issue_comment_url:
      "https://api.github.com/repos/dan/5by5-director/issues/comments{/number}",
    contents_url:
      "https://api.github.com/repos/dan/5by5-director/contents/{+path}",
    compare_url:
      "https://api.github.com/repos/dan/5by5-director/compare/{base}...{head}",
    merges_url: "https://api.github.com/repos/dan/5by5-director/merges",
    archive_url:
      "https://api.github.com/repos/dan/5by5-director/{archive_format}{/ref}",
    downloads_url: "https://api.github.com/repos/dan/5by5-director/downloads",
    issues_url:
      "https://api.github.com/repos/dan/5by5-director/issues{/number}",
    pulls_url: "https://api.github.com/repos/dan/5by5-director/pulls{/number}",
    milestones_url:
      "https://api.github.com/repos/dan/5by5-director/milestones{/number}",
    notifications_url:
      "https://api.github.com/repos/dan/5by5-director/notifications{?since,all,participating}",
    labels_url: "https://api.github.com/repos/dan/5by5-director/labels{/name}",
    releases_url:
      "https://api.github.com/repos/dan/5by5-director/releases{/id}",
    deployments_url:
      "https://api.github.com/repos/dan/5by5-director/deployments",
    created_at: "2022-01-26T15:53:40Z",
    updated_at: "2022-01-26T15:54:43Z",
    pushed_at: "2022-01-26T17:21:58Z",
    git_url: "git://github.com/dan/5by5-director.git",
    ssh_url: "git@github.com:dan/5by5-director.git",
    clone_url: "https://github.com/dan/5by5-director.git",
    svn_url: "https://github.com/dan/5by5-director",
    homepage: null,
    size: 19,
    stargazers_count: 0,
    watchers_count: 0,
    language: "Ruby",
    has_issues: true,
    has_projects: true,
    has_downloads: true,
    has_wiki: true,
    has_pages: false,
    has_discussions: false,
    forks_count: 0,
    mirror_url: null,
    archived: false,
    disabled: false,
    open_issues_count: 0,
    license: null,
    allow_forking: true,
    is_template: false,
    web_commit_signoff_required: false,
    topics: [],
    visibility: "public",
    forks: 0,
    open_issues: 0,
    watchers: 0,
    default_branch: "main",
    permissions: {
      admin: false,
      maintain: false,
      push: false,
      triage: false,
      pull: true,
    },
  },
  {
    id: 205440873,
    node_id: "MDEwOlJlcG9zaXRvcnkyMDU0NDA4NzM=",
    name: "datacenter_lookup",
    full_name: "dan/datacenter_lookup",
    private: false,
    owner: {
      login: "dan",
      id: 219,
      node_id: "MDQ6VXNlcjIxOQ==",
      avatar_url: "https://avatars.githubusercontent.com/u/219?v=4",
      gravatar_id: "",
      url: "https://api.github.com/users/dan",
      html_url: "https://github.com/dan",
      followers_url: "https://api.github.com/users/dan/followers",
      following_url: "https://api.github.com/users/dan/following{/other_user}",
      gists_url: "https://api.github.com/users/dan/gists{/gist_id}",
      starred_url: "https://api.github.com/users/dan/starred{/owner}{/repo}",
      subscriptions_url: "https://api.github.com/users/dan/subscriptions",
      organizations_url: "https://api.github.com/users/dan/orgs",
      repos_url: "https://api.github.com/users/dan/repos",
      events_url: "https://api.github.com/users/dan/events{/privacy}",
      received_events_url: "https://api.github.com/users/dan/received_events",
      type: "User",
      user_view_type: "public",
      site_admin: false,
    },
    html_url: "https://github.com/dan/datacenter_lookup",
    description:
      "An IP address parser in Ruby using the datacenters list from IPCat.",
    fork: false,
    url: "https://api.github.com/repos/dan/datacenter_lookup",
    forks_url: "https://api.github.com/repos/dan/datacenter_lookup/forks",
    keys_url:
      "https://api.github.com/repos/dan/datacenter_lookup/keys{/key_id}",
    collaborators_url:
      "https://api.github.com/repos/dan/datacenter_lookup/collaborators{/collaborator}",
    teams_url: "https://api.github.com/repos/dan/datacenter_lookup/teams",
    hooks_url: "https://api.github.com/repos/dan/datacenter_lookup/hooks",
    issue_events_url:
      "https://api.github.com/repos/dan/datacenter_lookup/issues/events{/number}",
    events_url: "https://api.github.com/repos/dan/datacenter_lookup/events",
    assignees_url:
      "https://api.github.com/repos/dan/datacenter_lookup/assignees{/user}",
    branches_url:
      "https://api.github.com/repos/dan/datacenter_lookup/branches{/branch}",
    tags_url: "https://api.github.com/repos/dan/datacenter_lookup/tags",
    blobs_url:
      "https://api.github.com/repos/dan/datacenter_lookup/git/blobs{/sha}",
    git_tags_url:
      "https://api.github.com/repos/dan/datacenter_lookup/git/tags{/sha}",
    git_refs_url:
      "https://api.github.com/repos/dan/datacenter_lookup/git/refs{/sha}",
    trees_url:
      "https://api.github.com/repos/dan/datacenter_lookup/git/trees{/sha}",
    statuses_url:
      "https://api.github.com/repos/dan/datacenter_lookup/statuses/{sha}",
    languages_url:
      "https://api.github.com/repos/dan/datacenter_lookup/languages",
    stargazers_url:
      "https://api.github.com/repos/dan/datacenter_lookup/stargazers",
    contributors_url:
      "https://api.github.com/repos/dan/datacenter_lookup/contributors",
    subscribers_url:
      "https://api.github.com/repos/dan/datacenter_lookup/subscribers",
    subscription_url:
      "https://api.github.com/repos/dan/datacenter_lookup/subscription",
    commits_url:
      "https://api.github.com/repos/dan/datacenter_lookup/commits{/sha}",
    git_commits_url:
      "https://api.github.com/repos/dan/datacenter_lookup/git/commits{/sha}",
    comments_url:
      "https://api.github.com/repos/dan/datacenter_lookup/comments{/number}",
    issue_comment_url:
      "https://api.github.com/repos/dan/datacenter_lookup/issues/comments{/number}",
    contents_url:
      "https://api.github.com/repos/dan/datacenter_lookup/contents/{+path}",
    compare_url:
      "https://api.github.com/repos/dan/datacenter_lookup/compare/{base}...{head}",
    merges_url: "https://api.github.com/repos/dan/datacenter_lookup/merges",
    archive_url:
      "https://api.github.com/repos/dan/datacenter_lookup/{archive_format}{/ref}",
    downloads_url:
      "https://api.github.com/repos/dan/datacenter_lookup/downloads",
    issues_url:
      "https://api.github.com/repos/dan/datacenter_lookup/issues{/number}",
    pulls_url:
      "https://api.github.com/repos/dan/datacenter_lookup/pulls{/number}",
    milestones_url:
      "https://api.github.com/repos/dan/datacenter_lookup/milestones{/number}",
    notifications_url:
      "https://api.github.com/repos/dan/datacenter_lookup/notifications{?since,all,participating}",
    labels_url:
      "https://api.github.com/repos/dan/datacenter_lookup/labels{/name}",
    releases_url:
      "https://api.github.com/repos/dan/datacenter_lookup/releases{/id}",
    deployments_url:
      "https://api.github.com/repos/dan/datacenter_lookup/deployments",
    created_at: "2019-08-30T18:59:09Z",
    updated_at: "2021-04-10T10:44:46Z",
    pushed_at: "2019-09-05T15:32:03Z",
    git_url: "git://github.com/dan/datacenter_lookup.git",
    ssh_url: "git@github.com:dan/datacenter_lookup.git",
    clone_url: "https://github.com/dan/datacenter_lookup.git",
    svn_url: "https://github.com/dan/datacenter_lookup",
    homepage: null,
    size: 53,
    stargazers_count: 2,
    watchers_count: 2,
    language: "Ruby",
    has_issues: true,
    has_projects: true,
    has_downloads: true,
    has_wiki: true,
    has_pages: false,
    has_discussions: false,
    forks_count: 2,
    mirror_url: null,
    archived: false,
    disabled: false,
    open_issues_count: 0,
    license: {
      key: "other",
      name: "Other",
      spdx_id: "NOASSERTION",
      url: null,
      node_id: "MDc6TGljZW5zZTA=",
    },
    allow_forking: true,
    is_template: false,
    web_commit_signoff_required: false,
    topics: [],
    visibility: "public",
    forks: 2,
    open_issues: 0,
    watchers: 2,
    default_branch: "master",
    permissions: {
      admin: false,
      maintain: false,
      push: false,
      triage: false,
      pull: true,
    },
  },
  {
    id: 40563197,
    node_id: "MDEwOlJlcG9zaXRvcnk0MDU2MzE5Nw==",
    name: "ingest",
    full_name: "dan/ingest",
    private: false,
    owner: {
      login: "dan",
      id: 219,
      node_id: "MDQ6VXNlcjIxOQ==",
      avatar_url: "https://avatars.githubusercontent.com/u/219?v=4",
      gravatar_id: "",
      url: "https://api.github.com/users/dan",
      html_url: "https://github.com/dan",
      followers_url: "https://api.github.com/users/dan/followers",
      following_url: "https://api.github.com/users/dan/following{/other_user}",
      gists_url: "https://api.github.com/users/dan/gists{/gist_id}",
      starred_url: "https://api.github.com/users/dan/starred{/owner}{/repo}",
      subscriptions_url: "https://api.github.com/users/dan/subscriptions",
      organizations_url: "https://api.github.com/users/dan/orgs",
      repos_url: "https://api.github.com/users/dan/repos",
      events_url: "https://api.github.com/users/dan/events{/privacy}",
      received_events_url: "https://api.github.com/users/dan/received_events",
      type: "User",
      user_view_type: "public",
      site_admin: false,
    },
    html_url: "https://github.com/dan/ingest",
    description:
      "Ingest is a library designed to help fetch and parse podcast RSS feeds.",
    fork: false,
    url: "https://api.github.com/repos/dan/ingest",
    forks_url: "https://api.github.com/repos/dan/ingest/forks",
    keys_url: "https://api.github.com/repos/dan/ingest/keys{/key_id}",
    collaborators_url:
      "https://api.github.com/repos/dan/ingest/collaborators{/collaborator}",
    teams_url: "https://api.github.com/repos/dan/ingest/teams",
    hooks_url: "https://api.github.com/repos/dan/ingest/hooks",
    issue_events_url:
      "https://api.github.com/repos/dan/ingest/issues/events{/number}",
    events_url: "https://api.github.com/repos/dan/ingest/events",
    assignees_url: "https://api.github.com/repos/dan/ingest/assignees{/user}",
    branches_url: "https://api.github.com/repos/dan/ingest/branches{/branch}",
    tags_url: "https://api.github.com/repos/dan/ingest/tags",
    blobs_url: "https://api.github.com/repos/dan/ingest/git/blobs{/sha}",
    git_tags_url: "https://api.github.com/repos/dan/ingest/git/tags{/sha}",
    git_refs_url: "https://api.github.com/repos/dan/ingest/git/refs{/sha}",
    trees_url: "https://api.github.com/repos/dan/ingest/git/trees{/sha}",
    statuses_url: "https://api.github.com/repos/dan/ingest/statuses/{sha}",
    languages_url: "https://api.github.com/repos/dan/ingest/languages",
    stargazers_url: "https://api.github.com/repos/dan/ingest/stargazers",
    contributors_url: "https://api.github.com/repos/dan/ingest/contributors",
    subscribers_url: "https://api.github.com/repos/dan/ingest/subscribers",
    subscription_url: "https://api.github.com/repos/dan/ingest/subscription",
    commits_url: "https://api.github.com/repos/dan/ingest/commits{/sha}",
    git_commits_url:
      "https://api.github.com/repos/dan/ingest/git/commits{/sha}",
    comments_url: "https://api.github.com/repos/dan/ingest/comments{/number}",
    issue_comment_url:
      "https://api.github.com/repos/dan/ingest/issues/comments{/number}",
    contents_url: "https://api.github.com/repos/dan/ingest/contents/{+path}",
    compare_url:
      "https://api.github.com/repos/dan/ingest/compare/{base}...{head}",
    merges_url: "https://api.github.com/repos/dan/ingest/merges",
    archive_url:
      "https://api.github.com/repos/dan/ingest/{archive_format}{/ref}",
    downloads_url: "https://api.github.com/repos/dan/ingest/downloads",
    issues_url: "https://api.github.com/repos/dan/ingest/issues{/number}",
    pulls_url: "https://api.github.com/repos/dan/ingest/pulls{/number}",
    milestones_url:
      "https://api.github.com/repos/dan/ingest/milestones{/number}",
    notifications_url:
      "https://api.github.com/repos/dan/ingest/notifications{?since,all,participating}",
    labels_url: "https://api.github.com/repos/dan/ingest/labels{/name}",
    releases_url: "https://api.github.com/repos/dan/ingest/releases{/id}",
    deployments_url: "https://api.github.com/repos/dan/ingest/deployments",
    created_at: "2015-08-11T20:18:52Z",
    updated_at: "2023-07-07T03:17:56Z",
    pushed_at: "2020-11-15T16:06:23Z",
    git_url: "git://github.com/dan/ingest.git",
    ssh_url: "git@github.com:dan/ingest.git",
    clone_url: "https://github.com/dan/ingest.git",
    svn_url: "https://github.com/dan/ingest",
    homepage: null,
    size: 105,
    stargazers_count: 13,
    watchers_count: 13,
    language: "Ruby",
    has_issues: true,
    has_projects: true,
    has_downloads: true,
    has_wiki: true,
    has_pages: false,
    has_discussions: false,
    forks_count: 1,
    mirror_url: null,
    archived: false,
    disabled: false,
    open_issues_count: 0,
    license: {
      key: "mit",
      name: "MIT License",
      spdx_id: "MIT",
      url: "https://api.github.com/licenses/mit",
      node_id: "MDc6TGljZW5zZTEz",
    },
    allow_forking: true,
    is_template: false,
    web_commit_signoff_required: false,
    topics: [],
    visibility: "public",
    forks: 1,
    open_issues: 0,
    watchers: 13,
    default_branch: "master",
    permissions: {
      admin: false,
      maintain: false,
      push: false,
      triage: false,
      pull: true,
    },
  },
  {
    id: 71372986,
    node_id: "MDEwOlJlcG9zaXRvcnk3MTM3Mjk4Ng==",
    name: "net-purgedomain",
    full_name: "dan/net-purgedomain",
    private: false,
    owner: {
      login: "dan",
      id: 219,
      node_id: "MDQ6VXNlcjIxOQ==",
      avatar_url: "https://avatars.githubusercontent.com/u/219?v=4",
      gravatar_id: "",
      url: "https://api.github.com/users/dan",
      html_url: "https://github.com/dan",
      followers_url: "https://api.github.com/users/dan/followers",
      following_url: "https://api.github.com/users/dan/following{/other_user}",
      gists_url: "https://api.github.com/users/dan/gists{/gist_id}",
      starred_url: "https://api.github.com/users/dan/starred{/owner}{/repo}",
      subscriptions_url: "https://api.github.com/users/dan/subscriptions",
      organizations_url: "https://api.github.com/users/dan/orgs",
      repos_url: "https://api.github.com/users/dan/repos",
      events_url: "https://api.github.com/users/dan/events{/privacy}",
      received_events_url: "https://api.github.com/users/dan/received_events",
      type: "User",
      user_view_type: "public",
      site_admin: false,
    },
    html_url: "https://github.com/dan/net-purgedomain",
    description:
      "Adds DOMAINPURGE to Net::HTTP for domain-level cache purging requests in Varnish.",
    fork: false,
    url: "https://api.github.com/repos/dan/net-purgedomain",
    forks_url: "https://api.github.com/repos/dan/net-purgedomain/forks",
    keys_url: "https://api.github.com/repos/dan/net-purgedomain/keys{/key_id}",
    collaborators_url:
      "https://api.github.com/repos/dan/net-purgedomain/collaborators{/collaborator}",
    teams_url: "https://api.github.com/repos/dan/net-purgedomain/teams",
    hooks_url: "https://api.github.com/repos/dan/net-purgedomain/hooks",
    issue_events_url:
      "https://api.github.com/repos/dan/net-purgedomain/issues/events{/number}",
    events_url: "https://api.github.com/repos/dan/net-purgedomain/events",
    assignees_url:
      "https://api.github.com/repos/dan/net-purgedomain/assignees{/user}",
    branches_url:
      "https://api.github.com/repos/dan/net-purgedomain/branches{/branch}",
    tags_url: "https://api.github.com/repos/dan/net-purgedomain/tags",
    blobs_url:
      "https://api.github.com/repos/dan/net-purgedomain/git/blobs{/sha}",
    git_tags_url:
      "https://api.github.com/repos/dan/net-purgedomain/git/tags{/sha}",
    git_refs_url:
      "https://api.github.com/repos/dan/net-purgedomain/git/refs{/sha}",
    trees_url:
      "https://api.github.com/repos/dan/net-purgedomain/git/trees{/sha}",
    statuses_url:
      "https://api.github.com/repos/dan/net-purgedomain/statuses/{sha}",
    languages_url: "https://api.github.com/repos/dan/net-purgedomain/languages",
    stargazers_url:
      "https://api.github.com/repos/dan/net-purgedomain/stargazers",
    contributors_url:
      "https://api.github.com/repos/dan/net-purgedomain/contributors",
    subscribers_url:
      "https://api.github.com/repos/dan/net-purgedomain/subscribers",
    subscription_url:
      "https://api.github.com/repos/dan/net-purgedomain/subscription",
    commits_url:
      "https://api.github.com/repos/dan/net-purgedomain/commits{/sha}",
    git_commits_url:
      "https://api.github.com/repos/dan/net-purgedomain/git/commits{/sha}",
    comments_url:
      "https://api.github.com/repos/dan/net-purgedomain/comments{/number}",
    issue_comment_url:
      "https://api.github.com/repos/dan/net-purgedomain/issues/comments{/number}",
    contents_url:
      "https://api.github.com/repos/dan/net-purgedomain/contents/{+path}",
    compare_url:
      "https://api.github.com/repos/dan/net-purgedomain/compare/{base}...{head}",
    merges_url: "https://api.github.com/repos/dan/net-purgedomain/merges",
    archive_url:
      "https://api.github.com/repos/dan/net-purgedomain/{archive_format}{/ref}",
    downloads_url: "https://api.github.com/repos/dan/net-purgedomain/downloads",
    issues_url:
      "https://api.github.com/repos/dan/net-purgedomain/issues{/number}",
    pulls_url:
      "https://api.github.com/repos/dan/net-purgedomain/pulls{/number}",
    milestones_url:
      "https://api.github.com/repos/dan/net-purgedomain/milestones{/number}",
    notifications_url:
      "https://api.github.com/repos/dan/net-purgedomain/notifications{?since,all,participating}",
    labels_url:
      "https://api.github.com/repos/dan/net-purgedomain/labels{/name}",
    releases_url:
      "https://api.github.com/repos/dan/net-purgedomain/releases{/id}",
    deployments_url:
      "https://api.github.com/repos/dan/net-purgedomain/deployments",
    created_at: "2016-10-19T15:42:40Z",
    updated_at: "2016-10-19T15:53:46Z",
    pushed_at: "2016-10-19T15:42:54Z",
    git_url: "git://github.com/dan/net-purgedomain.git",
    ssh_url: "git@github.com:dan/net-purgedomain.git",
    clone_url: "https://github.com/dan/net-purgedomain.git",
    svn_url: "https://github.com/dan/net-purgedomain",
    homepage: "",
    size: 2,
    stargazers_count: 0,
    watchers_count: 0,
    language: "Ruby",
    has_issues: true,
    has_projects: true,
    has_downloads: true,
    has_wiki: true,
    has_pages: false,
    has_discussions: false,
    forks_count: 1,
    mirror_url: null,
    archived: false,
    disabled: false,
    open_issues_count: 0,
    license: {
      key: "mit",
      name: "MIT License",
      spdx_id: "MIT",
      url: "https://api.github.com/licenses/mit",
      node_id: "MDc6TGljZW5zZTEz",
    },
    allow_forking: true,
    is_template: false,
    web_commit_signoff_required: false,
    topics: [],
    visibility: "public",
    forks: 1,
    open_issues: 0,
    watchers: 0,
    default_branch: "master",
    permissions: {
      admin: false,
      maintain: false,
      push: false,
      triage: false,
      pull: true,
    },
  },
  {
    id: 1181813,
    node_id: "MDEwOlJlcG9zaXRvcnkxMTgxODEz",
    name: "player",
    full_name: "dan/player",
    private: false,
    owner: {
      login: "dan",
      id: 219,
      node_id: "MDQ6VXNlcjIxOQ==",
      avatar_url: "https://avatars.githubusercontent.com/u/219?v=4",
      gravatar_id: "",
      url: "https://api.github.com/users/dan",
      html_url: "https://github.com/dan",
      followers_url: "https://api.github.com/users/dan/followers",
      following_url: "https://api.github.com/users/dan/following{/other_user}",
      gists_url: "https://api.github.com/users/dan/gists{/gist_id}",
      starred_url: "https://api.github.com/users/dan/starred{/owner}{/repo}",
      subscriptions_url: "https://api.github.com/users/dan/subscriptions",
      organizations_url: "https://api.github.com/users/dan/orgs",
      repos_url: "https://api.github.com/users/dan/repos",
      events_url: "https://api.github.com/users/dan/events{/privacy}",
      received_events_url: "https://api.github.com/users/dan/received_events",
      type: "User",
      user_view_type: "public",
      site_admin: false,
    },
    html_url: "https://github.com/dan/player",
    description: "Audio player for 5by5.tv",
    fork: false,
    url: "https://api.github.com/repos/dan/player",
    forks_url: "https://api.github.com/repos/dan/player/forks",
    keys_url: "https://api.github.com/repos/dan/player/keys{/key_id}",
    collaborators_url:
      "https://api.github.com/repos/dan/player/collaborators{/collaborator}",
    teams_url: "https://api.github.com/repos/dan/player/teams",
    hooks_url: "https://api.github.com/repos/dan/player/hooks",
    issue_events_url:
      "https://api.github.com/repos/dan/player/issues/events{/number}",
    events_url: "https://api.github.com/repos/dan/player/events",
    assignees_url: "https://api.github.com/repos/dan/player/assignees{/user}",
    branches_url: "https://api.github.com/repos/dan/player/branches{/branch}",
    tags_url: "https://api.github.com/repos/dan/player/tags",
    blobs_url: "https://api.github.com/repos/dan/player/git/blobs{/sha}",
    git_tags_url: "https://api.github.com/repos/dan/player/git/tags{/sha}",
    git_refs_url: "https://api.github.com/repos/dan/player/git/refs{/sha}",
    trees_url: "https://api.github.com/repos/dan/player/git/trees{/sha}",
    statuses_url: "https://api.github.com/repos/dan/player/statuses/{sha}",
    languages_url: "https://api.github.com/repos/dan/player/languages",
    stargazers_url: "https://api.github.com/repos/dan/player/stargazers",
    contributors_url: "https://api.github.com/repos/dan/player/contributors",
    subscribers_url: "https://api.github.com/repos/dan/player/subscribers",
    subscription_url: "https://api.github.com/repos/dan/player/subscription",
    commits_url: "https://api.github.com/repos/dan/player/commits{/sha}",
    git_commits_url:
      "https://api.github.com/repos/dan/player/git/commits{/sha}",
    comments_url: "https://api.github.com/repos/dan/player/comments{/number}",
    issue_comment_url:
      "https://api.github.com/repos/dan/player/issues/comments{/number}",
    contents_url: "https://api.github.com/repos/dan/player/contents/{+path}",
    compare_url:
      "https://api.github.com/repos/dan/player/compare/{base}...{head}",
    merges_url: "https://api.github.com/repos/dan/player/merges",
    archive_url:
      "https://api.github.com/repos/dan/player/{archive_format}{/ref}",
    downloads_url: "https://api.github.com/repos/dan/player/downloads",
    issues_url: "https://api.github.com/repos/dan/player/issues{/number}",
    pulls_url: "https://api.github.com/repos/dan/player/pulls{/number}",
    milestones_url:
      "https://api.github.com/repos/dan/player/milestones{/number}",
    notifications_url:
      "https://api.github.com/repos/dan/player/notifications{?since,all,participating}",
    labels_url: "https://api.github.com/repos/dan/player/labels{/name}",
    releases_url: "https://api.github.com/repos/dan/player/releases{/id}",
    deployments_url: "https://api.github.com/repos/dan/player/deployments",
    created_at: "2010-12-19T14:04:25Z",
    updated_at: "2023-01-28T17:27:33Z",
    pushed_at: "2011-01-03T21:12:49Z",
    git_url: "git://github.com/dan/player.git",
    ssh_url: "git@github.com:dan/player.git",
    clone_url: "https://github.com/dan/player.git",
    svn_url: "https://github.com/dan/player",
    homepage: "",
    size: 3696,
    stargazers_count: 3,
    watchers_count: 3,
    language: "JavaScript",
    has_issues: true,
    has_projects: true,
    has_downloads: true,
    has_wiki: false,
    has_pages: false,
    has_discussions: false,
    forks_count: 0,
    mirror_url: null,
    archived: true,
    disabled: false,
    open_issues_count: 0,
    license: null,
    allow_forking: true,
    is_template: false,
    web_commit_signoff_required: false,
    topics: [],
    visibility: "public",
    forks: 0,
    open_issues: 0,
    watchers: 3,
    default_branch: "master",
    permissions: {
      admin: false,
      maintain: false,
      push: false,
      triage: false,
      pull: true,
    },
  },
  {
    id: 201134123,
    node_id: "MDEwOlJlcG9zaXRvcnkyMDExMzQxMjM=",
    name: "podcast_agent_parser",
    full_name: "dan/podcast_agent_parser",
    private: false,
    owner: {
      login: "dan",
      id: 219,
      node_id: "MDQ6VXNlcjIxOQ==",
      avatar_url: "https://avatars.githubusercontent.com/u/219?v=4",
      gravatar_id: "",
      url: "https://api.github.com/users/dan",
      html_url: "https://github.com/dan",
      followers_url: "https://api.github.com/users/dan/followers",
      following_url: "https://api.github.com/users/dan/following{/other_user}",
      gists_url: "https://api.github.com/users/dan/gists{/gist_id}",
      starred_url: "https://api.github.com/users/dan/starred{/owner}{/repo}",
      subscriptions_url: "https://api.github.com/users/dan/subscriptions",
      organizations_url: "https://api.github.com/users/dan/orgs",
      repos_url: "https://api.github.com/users/dan/repos",
      events_url: "https://api.github.com/users/dan/events{/privacy}",
      received_events_url: "https://api.github.com/users/dan/received_events",
      type: "User",
      user_view_type: "public",
      site_admin: false,
    },
    html_url: "https://github.com/dan/podcast_agent_parser",
    description:
      "User agent parser written in Ruby using regex patterns from the Open Podcast Analytics Working Group.",
    fork: false,
    url: "https://api.github.com/repos/dan/podcast_agent_parser",
    forks_url: "https://api.github.com/repos/dan/podcast_agent_parser/forks",
    keys_url:
      "https://api.github.com/repos/dan/podcast_agent_parser/keys{/key_id}",
    collaborators_url:
      "https://api.github.com/repos/dan/podcast_agent_parser/collaborators{/collaborator}",
    teams_url: "https://api.github.com/repos/dan/podcast_agent_parser/teams",
    hooks_url: "https://api.github.com/repos/dan/podcast_agent_parser/hooks",
    issue_events_url:
      "https://api.github.com/repos/dan/podcast_agent_parser/issues/events{/number}",
    events_url: "https://api.github.com/repos/dan/podcast_agent_parser/events",
    assignees_url:
      "https://api.github.com/repos/dan/podcast_agent_parser/assignees{/user}",
    branches_url:
      "https://api.github.com/repos/dan/podcast_agent_parser/branches{/branch}",
    tags_url: "https://api.github.com/repos/dan/podcast_agent_parser/tags",
    blobs_url:
      "https://api.github.com/repos/dan/podcast_agent_parser/git/blobs{/sha}",
    git_tags_url:
      "https://api.github.com/repos/dan/podcast_agent_parser/git/tags{/sha}",
    git_refs_url:
      "https://api.github.com/repos/dan/podcast_agent_parser/git/refs{/sha}",
    trees_url:
      "https://api.github.com/repos/dan/podcast_agent_parser/git/trees{/sha}",
    statuses_url:
      "https://api.github.com/repos/dan/podcast_agent_parser/statuses/{sha}",
    languages_url:
      "https://api.github.com/repos/dan/podcast_agent_parser/languages",
    stargazers_url:
      "https://api.github.com/repos/dan/podcast_agent_parser/stargazers",
    contributors_url:
      "https://api.github.com/repos/dan/podcast_agent_parser/contributors",
    subscribers_url:
      "https://api.github.com/repos/dan/podcast_agent_parser/subscribers",
    subscription_url:
      "https://api.github.com/repos/dan/podcast_agent_parser/subscription",
    commits_url:
      "https://api.github.com/repos/dan/podcast_agent_parser/commits{/sha}",
    git_commits_url:
      "https://api.github.com/repos/dan/podcast_agent_parser/git/commits{/sha}",
    comments_url:
      "https://api.github.com/repos/dan/podcast_agent_parser/comments{/number}",
    issue_comment_url:
      "https://api.github.com/repos/dan/podcast_agent_parser/issues/comments{/number}",
    contents_url:
      "https://api.github.com/repos/dan/podcast_agent_parser/contents/{+path}",
    compare_url:
      "https://api.github.com/repos/dan/podcast_agent_parser/compare/{base}...{head}",
    merges_url: "https://api.github.com/repos/dan/podcast_agent_parser/merges",
    archive_url:
      "https://api.github.com/repos/dan/podcast_agent_parser/{archive_format}{/ref}",
    downloads_url:
      "https://api.github.com/repos/dan/podcast_agent_parser/downloads",
    issues_url:
      "https://api.github.com/repos/dan/podcast_agent_parser/issues{/number}",
    pulls_url:
      "https://api.github.com/repos/dan/podcast_agent_parser/pulls{/number}",
    milestones_url:
      "https://api.github.com/repos/dan/podcast_agent_parser/milestones{/number}",
    notifications_url:
      "https://api.github.com/repos/dan/podcast_agent_parser/notifications{?since,all,participating}",
    labels_url:
      "https://api.github.com/repos/dan/podcast_agent_parser/labels{/name}",
    releases_url:
      "https://api.github.com/repos/dan/podcast_agent_parser/releases{/id}",
    deployments_url:
      "https://api.github.com/repos/dan/podcast_agent_parser/deployments",
    created_at: "2019-08-07T22:02:05Z",
    updated_at: "2023-02-07T23:19:42Z",
    pushed_at: "2021-06-24T19:44:23Z",
    git_url: "git://github.com/dan/podcast_agent_parser.git",
    ssh_url: "git@github.com:dan/podcast_agent_parser.git",
    clone_url: "https://github.com/dan/podcast_agent_parser.git",
    svn_url: "https://github.com/dan/podcast_agent_parser",
    homepage: null,
    size: 45,
    stargazers_count: 3,
    watchers_count: 3,
    language: "Ruby",
    has_issues: true,
    has_projects: true,
    has_downloads: true,
    has_wiki: true,
    has_pages: false,
    has_discussions: false,
    forks_count: 0,
    mirror_url: null,
    archived: false,
    disabled: false,
    open_issues_count: 0,
    license: {
      key: "mit",
      name: "MIT License",
      spdx_id: "MIT",
      url: "https://api.github.com/licenses/mit",
      node_id: "MDc6TGljZW5zZTEz",
    },
    allow_forking: true,
    is_template: false,
    web_commit_signoff_required: false,
    topics: [],
    visibility: "public",
    forks: 0,
    open_issues: 0,
    watchers: 3,
    default_branch: "master",
    permissions: {
      admin: false,
      maintain: false,
      push: false,
      triage: false,
      pull: true,
    },
  },
  {
    id: 683218003,
    node_id: "R_kgDOKLkUUw",
    name: "shrine",
    full_name: "dan/shrine",
    private: false,
    owner: {
      login: "dan",
      id: 219,
      node_id: "MDQ6VXNlcjIxOQ==",
      avatar_url: "https://avatars.githubusercontent.com/u/219?v=4",
      gravatar_id: "",
      url: "https://api.github.com/users/dan",
      html_url: "https://github.com/dan",
      followers_url: "https://api.github.com/users/dan/followers",
      following_url: "https://api.github.com/users/dan/following{/other_user}",
      gists_url: "https://api.github.com/users/dan/gists{/gist_id}",
      starred_url: "https://api.github.com/users/dan/starred{/owner}{/repo}",
      subscriptions_url: "https://api.github.com/users/dan/subscriptions",
      organizations_url: "https://api.github.com/users/dan/orgs",
      repos_url: "https://api.github.com/users/dan/repos",
      events_url: "https://api.github.com/users/dan/events{/privacy}",
      received_events_url: "https://api.github.com/users/dan/received_events",
      type: "User",
      user_view_type: "public",
      site_admin: false,
    },
    html_url: "https://github.com/dan/shrine",
    description: "File Attachment toolkit for Ruby applications",
    fork: true,
    url: "https://api.github.com/repos/dan/shrine",
    forks_url: "https://api.github.com/repos/dan/shrine/forks",
    keys_url: "https://api.github.com/repos/dan/shrine/keys{/key_id}",
    collaborators_url:
      "https://api.github.com/repos/dan/shrine/collaborators{/collaborator}",
    teams_url: "https://api.github.com/repos/dan/shrine/teams",
    hooks_url: "https://api.github.com/repos/dan/shrine/hooks",
    issue_events_url:
      "https://api.github.com/repos/dan/shrine/issues/events{/number}",
    events_url: "https://api.github.com/repos/dan/shrine/events",
    assignees_url: "https://api.github.com/repos/dan/shrine/assignees{/user}",
    branches_url: "https://api.github.com/repos/dan/shrine/branches{/branch}",
    tags_url: "https://api.github.com/repos/dan/shrine/tags",
    blobs_url: "https://api.github.com/repos/dan/shrine/git/blobs{/sha}",
    git_tags_url: "https://api.github.com/repos/dan/shrine/git/tags{/sha}",
    git_refs_url: "https://api.github.com/repos/dan/shrine/git/refs{/sha}",
    trees_url: "https://api.github.com/repos/dan/shrine/git/trees{/sha}",
    statuses_url: "https://api.github.com/repos/dan/shrine/statuses/{sha}",
    languages_url: "https://api.github.com/repos/dan/shrine/languages",
    stargazers_url: "https://api.github.com/repos/dan/shrine/stargazers",
    contributors_url: "https://api.github.com/repos/dan/shrine/contributors",
    subscribers_url: "https://api.github.com/repos/dan/shrine/subscribers",
    subscription_url: "https://api.github.com/repos/dan/shrine/subscription",
    commits_url: "https://api.github.com/repos/dan/shrine/commits{/sha}",
    git_commits_url:
      "https://api.github.com/repos/dan/shrine/git/commits{/sha}",
    comments_url: "https://api.github.com/repos/dan/shrine/comments{/number}",
    issue_comment_url:
      "https://api.github.com/repos/dan/shrine/issues/comments{/number}",
    contents_url: "https://api.github.com/repos/dan/shrine/contents/{+path}",
    compare_url:
      "https://api.github.com/repos/dan/shrine/compare/{base}...{head}",
    merges_url: "https://api.github.com/repos/dan/shrine/merges",
    archive_url:
      "https://api.github.com/repos/dan/shrine/{archive_format}{/ref}",
    downloads_url: "https://api.github.com/repos/dan/shrine/downloads",
    issues_url: "https://api.github.com/repos/dan/shrine/issues{/number}",
    pulls_url: "https://api.github.com/repos/dan/shrine/pulls{/number}",
    milestones_url:
      "https://api.github.com/repos/dan/shrine/milestones{/number}",
    notifications_url:
      "https://api.github.com/repos/dan/shrine/notifications{?since,all,participating}",
    labels_url: "https://api.github.com/repos/dan/shrine/labels{/name}",
    releases_url: "https://api.github.com/repos/dan/shrine/releases{/id}",
    deployments_url: "https://api.github.com/repos/dan/shrine/deployments",
    created_at: "2023-08-25T22:18:34Z",
    updated_at: "2023-08-25T22:19:55Z",
    pushed_at: "2023-08-25T22:19:49Z",
    git_url: "git://github.com/dan/shrine.git",
    ssh_url: "git@github.com:dan/shrine.git",
    clone_url: "https://github.com/dan/shrine.git",
    svn_url: "https://github.com/dan/shrine",
    homepage: "https://shrinerb.com",
    size: 6034,
    stargazers_count: 0,
    watchers_count: 0,
    language: "Ruby",
    has_issues: false,
    has_projects: true,
    has_downloads: true,
    has_wiki: true,
    has_pages: false,
    has_discussions: false,
    forks_count: 0,
    mirror_url: null,
    archived: false,
    disabled: false,
    open_issues_count: 0,
    license: {
      key: "mit",
      name: "MIT License",
      spdx_id: "MIT",
      url: "https://api.github.com/licenses/mit",
      node_id: "MDc6TGljZW5zZTEz",
    },
    allow_forking: true,
    is_template: false,
    web_commit_signoff_required: false,
    topics: [],
    visibility: "public",
    forks: 0,
    open_issues: 0,
    watchers: 0,
    default_branch: "master",
    permissions: {
      admin: false,
      maintain: false,
      push: false,
      triage: false,
      pull: true,
    },
  },
];
