export const USERS_MOCK = {
  total_count: 796502,
  incomplete_results: false,
  items: [
    {
      login: "dan",
      id: 219,
      node_id: "MDQ6VXNlcjIxOQ==",
      avatar_url: "https://avatars.githubusercontent.com/u/219?v=4",
      gravatar_id: "",
      url: "https://api.github.com/users/dan",
      html_url: "https://github.com/dan",
      followers_url: "https://api.github.com/users/dan/followers",
      following_url: "https://api.github.com/users/dan/following{/other_user}",
      gists_url: "https://api.github.com/users/dan/gists{/gist_id}",
      starred_url: "https://api.github.com/users/dan/starred{/owner}{/repo}",
      subscriptions_url: "https://api.github.com/users/dan/subscriptions",
      organizations_url: "https://api.github.com/users/dan/orgs",
      repos_url: "https://api.github.com/users/dan/repos",
      events_url: "https://api.github.com/users/dan/events{/privacy}",
      received_events_url: "https://api.github.com/users/dan/received_events",
      type: "User",
      user_view_type: "public",
      site_admin: false,
      score: 1,
    },
    {
      login: "gaearon",
      id: 810438,
      node_id: "MDQ6VXNlcjgxMDQzOA==",
      avatar_url: "https://avatars.githubusercontent.com/u/810438?v=4",
      gravatar_id: "",
      url: "https://api.github.com/users/gaearon",
      html_url: "https://github.com/gaearon",
      followers_url: "https://api.github.com/users/gaearon/followers",
      following_url:
        "https://api.github.com/users/gaearon/following{/other_user}",
      gists_url: "https://api.github.com/users/gaearon/gists{/gist_id}",
      starred_url:
        "https://api.github.com/users/gaearon/starred{/owner}{/repo}",
      subscriptions_url: "https://api.github.com/users/gaearon/subscriptions",
      organizations_url: "https://api.github.com/users/gaearon/orgs",
      repos_url: "https://api.github.com/users/gaearon/repos",
      events_url: "https://api.github.com/users/gaearon/events{/privacy}",
      received_events_url:
        "https://api.github.com/users/gaearon/received_events",
      type: "User",
      user_view_type: "public",
      site_admin: false,
      score: 1,
    },
    {
      login: "taikoxyz",
      id: 99078433,
      node_id: "O_kgDOBefRIQ",
      avatar_url: "https://avatars.githubusercontent.com/u/99078433?v=4",
      gravatar_id: "",
      url: "https://api.github.com/users/taikoxyz",
      html_url: "https://github.com/taikoxyz",
      followers_url: "https://api.github.com/users/taikoxyz/followers",
      following_url:
        "https://api.github.com/users/taikoxyz/following{/other_user}",
      gists_url: "https://api.github.com/users/taikoxyz/gists{/gist_id}",
      starred_url:
        "https://api.github.com/users/taikoxyz/starred{/owner}{/repo}",
      subscriptions_url: "https://api.github.com/users/taikoxyz/subscriptions",
      organizations_url: "https://api.github.com/users/taikoxyz/orgs",
      repos_url: "https://api.github.com/users/taikoxyz/repos",
      events_url: "https://api.github.com/users/taikoxyz/events{/privacy}",
      received_events_url:
        "https://api.github.com/users/taikoxyz/received_events",
      type: "Organization",
      user_view_type: "public",
      site_admin: false,
      score: 1,
    },
    {
      login: "danvega",
      id: 349507,
      node_id: "MDQ6VXNlcjM0OTUwNw==",
      avatar_url: "https://avatars.githubusercontent.com/u/349507?v=4",
      gravatar_id: "",
      url: "https://api.github.com/users/danvega",
      html_url: "https://github.com/danvega",
      followers_url: "https://api.github.com/users/danvega/followers",
      following_url:
        "https://api.github.com/users/danvega/following{/other_user}",
      gists_url: "https://api.github.com/users/danvega/gists{/gist_id}",
      starred_url:
        "https://api.github.com/users/danvega/starred{/owner}{/repo}",
      subscriptions_url: "https://api.github.com/users/danvega/subscriptions",
      organizations_url: "https://api.github.com/users/danvega/orgs",
      repos_url: "https://api.github.com/users/danvega/repos",
      events_url: "https://api.github.com/users/danvega/events{/privacy}",
      received_events_url:
        "https://api.github.com/users/danvega/received_events",
      type: "User",
      user_view_type: "public",
      site_admin: false,
      score: 1,
    },
    {
      login: "DanWahlin",
      id: 1767249,
      node_id: "MDQ6VXNlcjE3NjcyNDk=",
      avatar_url: "https://avatars.githubusercontent.com/u/1767249?v=4",
      gravatar_id: "",
      url: "https://api.github.com/users/DanWahlin",
      html_url: "https://github.com/DanWahlin",
      followers_url: "https://api.github.com/users/DanWahlin/followers",
      following_url:
        "https://api.github.com/users/DanWahlin/following{/other_user}",
      gists_url: "https://api.github.com/users/DanWahlin/gists{/gist_id}",
      starred_url:
        "https://api.github.com/users/DanWahlin/starred{/owner}{/repo}",
      subscriptions_url: "https://api.github.com/users/DanWahlin/subscriptions",
      organizations_url: "https://api.github.com/users/DanWahlin/orgs",
      repos_url: "https://api.github.com/users/DanWahlin/repos",
      events_url: "https://api.github.com/users/DanWahlin/events{/privacy}",
      received_events_url:
        "https://api.github.com/users/DanWahlin/received_events",
      type: "User",
      user_view_type: "public",
      site_admin: false,
      score: 1,
    },
  ],
};
